name: 'Netlify Deploy'
author: 'Jo Colina'
description: 'Netlify Deploy'

inputs:
  NETLIFY_AUTH_TOKEN:
    description: 'Auth token to use with netlify'
    required: true
    default: ''

  NETLIFY_SITE_ID:
    description: 'Your Netlify site id'
    required: true
    default: ''

  NETLIFY_DEPLOY_TO_PROD:
    description: 'Should the site be deployed to production?'
    required: false
    default: false

  NETLIFY_DEPLOY_MESSAGE:
    description: 'A deploy message'
    required: false
    default: ''

  build_directory:
    description: 'Directory where built files are stored'
    required: true
    default: 'build'

  functions_directory:
    description: 'Directory where built files are stored'
    required: false
    default: ''

  install_command:
    description: 'Command to install dependencies'
    required: false
    default: ''

  build_command:
    description: 'Command to build static website'
    required: false
    default: 'npm run build'

  deploy_alias:
    description: 'Deployment Subdomain name'
    required: false
    default: ''

  node_version:
    description: 'Node version or arguments compatible with `nvm install`'
    required: false
    default: ''

outputs:
  NETLIFY_OUTPUT:
    description: "netlify command output"
  NETLIFY_URL:
    description: "deployment URL"
  NETLIFY_LOGS_URL:
    description: "deployment preview logs url"
  NETLIFY_LIVE_URL:
    description: "deployment preview URL"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.NETLIFY_AUTH_TOKEN }}
    - ${{ inputs.NETLIFY_SITE_ID }}
    - ${{ inputs.NETLIFY_DEPLOY_TO_PROD }}
    - ${{ inputs.build_directory }}
    - ${{ inputs.functions_directory }}
    - ${{ inputs.install_command }}
    - ${{ inputs.build_command }}
    - ${{ inputs.deploy_alias }}
    - ${{ inputs.node_version }}

branding:
  icon: activity
  color: blue
